<?php
/**
 * UpdateEmailCampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SendinBlue\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SendinBlue\Client;

/**
 * UpdateEmailCampaignTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateEmailCampaign
 * @package     SendinBlue\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateEmailCampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateEmailCampaign"
     */
    public function testUpdateEmailCampaign()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "htmlContent"
     */
    public function testPropertyHtmlContent()
    {
    }

    /**
     * Test attribute "htmlUrl"
     */
    public function testPropertyHtmlUrl()
    {
    }

    /**
     * Test attribute "scheduledAt"
     */
    public function testPropertyScheduledAt()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "replyTo"
     */
    public function testPropertyReplyTo()
    {
    }

    /**
     * Test attribute "toField"
     */
    public function testPropertyToField()
    {
    }

    /**
     * Test attribute "recipients"
     */
    public function testPropertyRecipients()
    {
    }

    /**
     * Test attribute "attachmentUrl"
     */
    public function testPropertyAttachmentUrl()
    {
    }

    /**
     * Test attribute "inlineImageActivation"
     */
    public function testPropertyInlineImageActivation()
    {
    }

    /**
     * Test attribute "mirrorActive"
     */
    public function testPropertyMirrorActive()
    {
    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {
    }

    /**
     * Test attribute "footer"
     */
    public function testPropertyFooter()
    {
    }

    /**
     * Test attribute "header"
     */
    public function testPropertyHeader()
    {
    }

    /**
     * Test attribute "utmCampaign"
     */
    public function testPropertyUtmCampaign()
    {
    }

    /**
     * Test attribute "params"
     */
    public function testPropertyParams()
    {
    }

    /**
     * Test attribute "sendAtBestTime"
     */
    public function testPropertySendAtBestTime()
    {
    }

    /**
     * Test attribute "abTesting"
     */
    public function testPropertyAbTesting()
    {
    }

    /**
     * Test attribute "subjectA"
     */
    public function testPropertySubjectA()
    {
    }

    /**
     * Test attribute "subjectB"
     */
    public function testPropertySubjectB()
    {
    }

    /**
     * Test attribute "splitRule"
     */
    public function testPropertySplitRule()
    {
    }

    /**
     * Test attribute "winnerCriteria"
     */
    public function testPropertyWinnerCriteria()
    {
    }

    /**
     * Test attribute "winnerDelay"
     */
    public function testPropertyWinnerDelay()
    {
    }

    /**
     * Test attribute "ipWarmupEnable"
     */
    public function testPropertyIpWarmupEnable()
    {
    }

    /**
     * Test attribute "initialQuota"
     */
    public function testPropertyInitialQuota()
    {
    }

    /**
     * Test attribute "increaseRate"
     */
    public function testPropertyIncreaseRate()
    {
    }
}
